// Builds worker/worker.js (one file to paste into Cloudflare) from the shared due logic + web push + main.
import fs from 'node:fs';
const here = new URL('.', import.meta.url).pathname;
const strip = (s) => s.replace(/^export (const|function|async function) /gm, '$1 ').replace(/^export \{[^}]*\};?\n/gm, '');
const due = strip(fs.readFileSync(here + '../sender/due.mjs', 'utf8'));
const push = fs.readFileSync(here + 'webpush-web.js', 'utf8');
const main = fs.readFileSync(here + 'main.js', 'utf8');
fs.writeFileSync(here + 'worker.js', `// GENERATED by worker/build.mjs. Do not edit; edit the sources and rebuild.\n\n${due}\n${push}\n${main}`);
console.log('built worker.js', fs.statSync(here + 'worker.js').size, 'bytes');
