// GENERATED by worker/build.mjs. Do not edit; edit the sources and rebuild.

// Decides which reminders fire inside a time window. Pure functions, no network.
const pad = (n) => String(n).padStart(2, '0');

function offsetMs(epoch, tz) {
  const p = Object.fromEntries(new Intl.DateTimeFormat('en-US', { timeZone: tz, hourCycle: 'h23', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }).formatToParts(new Date(epoch)).map((x) => [x.type, x.value]));
  return Date.UTC(p.year, p.month - 1, p.day, p.hour, p.minute, p.second) - Math.floor(epoch / 1000) * 1000;
}

// Epoch ms of a wall-clock date + time in a time zone.
function zonedEpoch(date, time, tz) {
  const [y, m, d] = date.split('-').map(Number); const [hh, mm] = time.split(':').map(Number);
  const guess = Date.UTC(y, m - 1, d, hh, mm);
  let t = guess - offsetMs(guess, tz);
  t = guess - offsetMs(t, tz);
  return t;
}

function localDate(epoch, tz) {
  const p = Object.fromEntries(new Intl.DateTimeFormat('en-US', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(epoch)).map((x) => [x.type, x.value]));
  return `${p.year}-${p.month}-${p.day}`;
}
const addDays = (s, n) => { const [y, m, d] = s.split('-').map(Number); const t = new Date(Date.UTC(y, m - 1, d + n)); return `${t.getUTCFullYear()}-${pad(t.getUTCMonth() + 1)}-${pad(t.getUTCDate())}`; };
const weekday = (s) => { const [y, m, d] = s.split('-').map(Number); return new Date(Date.UTC(y, m - 1, d)).getUTCDay(); };
const live = (c) => Object.values(c || {}).filter((r) => r && !r.deleted);

function habitDue(h, date) {
  if (date < h.startDate) return false;
  const s = h.schedule || { freq: 'daily' };
  if (s.freq === 'weekly') return (s.days || []).includes(weekday(date));
  if ((s.interval || 1) > 1) return Math.round((Date.parse(date) - Date.parse(h.startDate)) / 864e5) % s.interval === 0;
  return true;
}
function habitDone(db, h, date) {
  const l = db.logs?.[`${h.id}|${date}`];
  if (!l || l.deleted) return false;
  return h.type === 'check' ? !!l.done : (l.value || 0) >= h.goal;
}
const fmtTime = (t) => { const [h, m] = t.split(':').map(Number); return `${((h + 11) % 12) + 1}:${pad(m)} ${h >= 12 ? 'PM' : 'AM'}`; };

// from < fire <= to. A reminder never fires for something edited after its fire time (no retroactive pings).
function computeDue(db, { from, to, tz, defaultTime = '09:00' }) {
  const out = [];
  const lists = db.lists || {};
  for (const t of live(db.tasks)) {
    if (t.done || t.reminder === null || t.reminder === undefined || !t.date) continue;
    if (lists[t.listId]?.kind === 'notes') continue;
    const fire = zonedEpoch(t.date, t.time || defaultTime, tz) - t.reminder * 60000;
    if (fire <= from || fire > to || fire <= Date.parse(t.updatedAt || 0)) continue;
    const list = lists[t.listId]?.name;
    const when = t.reminder ? `Due ${t.time ? fmtTime(t.time) : 'today'}` : (t.time ? fmtTime(t.time) : 'Due today');
    out.push({ fire, key: `t:${t.id}:${fire}`, title: t.title || 'Task', body: [when, list].filter(Boolean).join(' · '), url: `./#/today`, tag: `task-${t.id}` });
  }
  const days = [localDate(from, tz), localDate(to, tz)];
  const dates = [...new Set(days)];
  for (const h of live(db.habits)) {
    if (h.archived || !(h.reminders || []).length) continue;
    for (const date of dates) {
      if (!habitDue(h, date) || habitDone(db, h, date)) continue;
      for (const r of h.reminders) {
        const fire = zonedEpoch(date, r, tz);
        if (fire <= from || fire > to || fire <= Date.parse(h.updatedAt || 0)) continue;
        out.push({ fire, key: `h:${h.id}:${date}:${r}`, title: h.name, body: h.type === 'amount' ? `Goal: ${h.goal}${h.unit && h.unit !== 'Count' ? ' ' + h.unit : ''}. Not logged yet.` : 'Not done yet today.', url: `./#/habits`, tag: `habit-${h.id}` });
      }
    }
  }
  return out;
}

// Web Push for Cloudflare Workers / browsers: WebCrypto only (RFC 8291 aes128gcm + RFC 8292 VAPID).
const enc = new TextEncoder();
const toB64u = (buf) => { let s = ''; new Uint8Array(buf).forEach((b) => { s += String.fromCharCode(b); }); return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); };
const fromB64u = (s) => { const p = '='.repeat((4 - (s.length % 4)) % 4); const b = atob((s + p).replace(/-/g, '+').replace(/_/g, '/')); return Uint8Array.from(b, (c) => c.charCodeAt(0)); };
const concat = (...parts) => { const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0)); let o = 0; parts.forEach((p) => { out.set(p, o); o += p.length; }); return out; };

async function hkdf(ikm, salt, info, bytes) {
  const key = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  return new Uint8Array(await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt, info }, key, bytes * 8));
}

async function vapidJwt(endpoint, subject, publicKey, privateKey) {
  const pub = fromB64u(publicKey);
  const key = await crypto.subtle.importKey('jwk', { kty: 'EC', crv: 'P-256', d: privateKey, x: toB64u(pub.slice(1, 33)), y: toB64u(pub.slice(33, 65)) }, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
  const head = toB64u(enc.encode(JSON.stringify({ typ: 'JWT', alg: 'ES256' })));
  const body = toB64u(enc.encode(JSON.stringify({ aud: new URL(endpoint).origin, exp: Math.floor(Date.now() / 1000) + 12 * 3600, sub: subject })));
  const sig = await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, enc.encode(`${head}.${body}`));
  return `${head}.${body}.${toB64u(sig)}`;
}

async function encryptPayload(sub, payload) {
  const uaPublic = fromB64u(sub.keys.p256dh);
  const auth = fromB64u(sub.keys.auth);
  const pair = await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']);
  const asPublic = new Uint8Array(await crypto.subtle.exportKey('raw', pair.publicKey));
  const uaKey = await crypto.subtle.importKey('raw', uaPublic, { name: 'ECDH', namedCurve: 'P-256' }, false, []);
  const secret = new Uint8Array(await crypto.subtle.deriveBits({ name: 'ECDH', public: uaKey }, pair.privateKey, 256));
  const ikm = await hkdf(secret, auth, concat(enc.encode('WebPush: info\0'), uaPublic, asPublic), 32);
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const cek = await hkdf(ikm, salt, enc.encode('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdf(ikm, salt, enc.encode('Content-Encoding: nonce\0'), 12);
  const aes = await crypto.subtle.importKey('raw', cek, 'AES-GCM', false, ['encrypt']);
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aes, concat(enc.encode(payload), new Uint8Array([2]))));
  const rs = new Uint8Array([0, 0, 0x10, 0]); // record size 4096
  return concat(salt, rs, new Uint8Array([asPublic.length]), asPublic, ct);
}

// Resolves to the push service's HTTP status (201 = accepted, 404/410 = subscription gone).
async function sendPush(sub, payload, { subject, publicKey, privateKey, ttl = 3600 }) {
  const body = await encryptPayload(sub, JSON.stringify(payload));
  const jwt = await vapidJwt(sub.endpoint, subject, publicKey, privateKey);
  const res = await fetch(sub.endpoint, { method: 'POST', headers: { Authorization: `vapid t=${jwt}, k=${publicKey}`, 'Content-Encoding': 'aes128gcm', 'Content-Type': 'application/octet-stream', TTL: String(ttl), Urgency: 'high' }, body });
  return res.status;
}

// Cloudflare Worker: runs every minute (cron trigger), reads the private data repo, sends due reminders.
// Secrets: DATA_TOKEN (GitHub fine-grained token, Contents read/write on daybook-data), VAPID_PRIVATE_KEY.
const CATCHUP = 30 * 60e3;   // after an outage, catch up on up to 30 minutes
const COLD_START = 5 * 60e3; // first ever run

const b64dec = (s) => new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\n/g, '')), (c) => c.charCodeAt(0)));
const b64enc = (s) => { let r = ''; new TextEncoder().encode(s).forEach((b) => { r += String.fromCharCode(b); }); return btoa(r); };

async function run(env) {
  const REPO = env.DATA_REPO || 'manangupta1995/daybook-data';
  const gh = (path, opts = {}) => fetch(`https://api.github.com/repos/${REPO}/contents/${path}`, { ...opts, headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${env.DATA_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'daybook-reminders', ...(opts.headers || {}) } });
  const getJson = async (path) => {
    const r = await gh(path);
    if (r.status === 404) return { data: null, sha: null };
    if (!r.ok) throw new Error(`GET ${path}: ${r.status}`);
    const j = await r.json();
    return { data: JSON.parse(b64dec(j.content)), sha: j.sha };
  };
  const putJson = async (path, data, sha, message) => (await gh(path, { method: 'PUT', body: JSON.stringify({ message, content: b64enc(JSON.stringify(data, null, 1) + '\n'), ...(sha ? { sha } : {}) }) })).status;

  if (!env.DATA_TOKEN || !env.VAPID_PRIVATE_KEY) { console.log('Missing DATA_TOKEN or VAPID_PRIVATE_KEY'); return { sent: 0 }; }
  const now = Date.now();
  const [{ data: db }, { data: state, sha: stateSha }] = await Promise.all([getJson('data.json'), getJson('state.json')]);
  if (!db) return { sent: 0 };
  const publicKey = db.config?.push?.publicKey;
  const devices = Object.values(db.devices || {}).filter((d) => !d.deleted && d.endpoint);
  if (!publicKey || !devices.length) return { sent: 0 };

  const from = Math.max(state?.lastRun ?? now - COLD_START, now - CATCHUP);
  const tz = devices[0].tz || 'America/Los_Angeles';
  const fmt = (e) => new Intl.DateTimeFormat('en-US', { timeZone: tz, hour: 'numeric', minute: '2-digit' }).format(new Date(e));
  const due = computeDue(db, { from, to: now, tz }).map((n) => (now - n.fire > 10 * 60e3 ? { ...n, body: `Missed at ${fmt(n.fire)}. ${n.body}` } : n));
  if (!due.length) return { sent: 0 };

  const gone = new Set(); let sent = 0;
  for (const d of devices) {
    for (const n of due) {
      try {
        const status = await sendPush({ endpoint: d.endpoint, keys: d.keys }, { title: n.title, body: n.body, url: n.url, tag: n.tag }, { subject: env.VAPID_SUBJECT || 'https://manangupta1995.github.io/daybook/', publicKey, privateKey: env.VAPID_PRIVATE_KEY });
        if (status === 404 || status === 410) { gone.add(d.id); break; }
        if (status >= 200 && status < 300) sent++; else console.log(`push service answered ${status}`);
      } catch (e) { console.log('send failed', e.message); }
    }
  }
  console.log(`due ${due.length}, sent ${sent}`);
  const code = await putJson('state.json', { lastRun: now }, stateSha, 'reminders: advance window');
  if (code >= 300) console.log(`state write answered ${code}`);
  for (let i = 0; gone.size && i < 3; i++) {
    const { data: fresh, sha } = await getJson('data.json');
    const stamp = new Date().toISOString();
    gone.forEach((id) => { if (fresh.devices?.[id]) fresh.devices[id] = { id, deleted: true, updatedAt: stamp }; });
    fresh.updatedAt = stamp;
    if ((await putJson('data.json', fresh, sha, 'reminders: remove expired device')) < 300) break;
  }
  return { sent };
}

export default {
  async scheduled(event, env, ctx) { ctx.waitUntil(run(env).catch((e) => console.log('run failed:', e.message))); },
  async fetch(request, env) { // visiting the worker URL runs a check and reports (useful for a first test)
    try { const r = await run(env); return new Response(`ok, sent ${r.sent}\n`); } catch (e) { return new Response(`error: ${e.message}\n`, { status: 500 }); }
  },
};
export { run };
